mySiteRuby/config/routes.rb
Rails.application.routes.draw do

  get 'articles/index', to: 'articles#index', as: :index_articles
  get 'articles/edit', to: 'articles#edit', as: :edit_articles
  
  root to: 'welcome#index', as: :index
  get '/home', to: 'home#index', as: :home

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :articles, only: [:new, :create, :edit, :index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :users, only: [:new, :create, :edit] do
    member do
      get 'confirm'
    end
  end
  
  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users, except: [:show]
  end

end

mySiteRuby/app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user, foreign_key: "users_id"

end

mySiteRuby/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index

  end

  def new
    @articles = Article.new
  end

  def create
    article_params = params.require(:article).permit(:name, :bio, :image, :user_id)
    @article = Article.new(article_params)

    @article.users_id = current_user.id
    if @article.valid?
      @article.save
      redirect_to index_articles_path, success: 'Votre article à bien été créer'
    else
      render 'new'
    end   
  end

  def edit 
    @article = current_user
  end

  def update 
    article_params = params.require(:article).permit(:name, :bio, :image)
    if @article.update(article_params)
      redirect_to edit_articles_path, success: 'Votre article à bien été mis à jour !'
    else
      render :edit
    end
  end

end

mySiteRuby/app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

mySiteRuby/app/views/articles/index.html.erb
<div class="container mt-3">
    <h1 class="text-center">Vos Articles de chats</h1>
    <%= link_to 'Créer un nouvel Articles', new_article_path, class: "text-center" %>
</div>

mySiteRuby/app/views/articles/new.html.erb
<div class="mt-3">
  <div class="row justify-content-center">
    <section class="col-lg-5">
        <div class="col-xs-12">
            <h3>Créer un nouvel article</h3>
            <%= form_for @articles do |form| %>

              <% if @articles.errors.any? %>
                  <div class="alert alert-danger">
                      <ul>
                      <% @articles.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                      </ul>
                  </div>
              <% end %>

              <div class="input-group mb-2">
                  <%= form.file_field :image, placeholder: "Image" , :class => "form-control"%> 
              </div>
              <div class="input-group mb-2">
                  <%= form.text_field :name, placeholder: "Nom de l'article" , :class => "form-control"%> 
              </div>
              <div class="input-group mb-2">
                  <%= form.text_field :bio, placeholder: "Bio" , :class => "form-control"%> 
              </div>
              <div class="form-group">
                  <button type="submit" class="btn btn-primary">Modifier l'article</button>
              </div>
          <% end %>
        </div>       
    </section>
  </div>
</div>