mySiteRuby/config/routes.rb
Rails.application.routes.draw do

  get 'articles/index', to: 'articles#index', as: :index_articles
  get 'articles/edit', to: 'articles#edit', as: :edit_articles
  
  root to: 'welcome#index', as: :index
  get '/home', to: 'home#index', as: :home

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :articles, only: [:new, :create, :edit, :index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :users, only: [:new, :create, :edit] do
    member do
      get 'confirm'
    end
  end
  
  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users, except: [:show]
  end

end

mySiteRuby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySiteRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">    
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= index_path %>">MySiteRuby</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if isAdmin? %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Gestion des utilisateurs', [:admin, User], class: "nav-link" %>
            </li>
          </ul>
        <%end%>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to 'Mon profil', profil_path, :class => "dropdown-item" %>
                <%= link_to 'Articles', index_articles_path, :class => "dropdown-item" %>
                <%= link_to 'home', home_path, :class => "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Se déconnecter', destroy_session_path, data: {method: :delete}, :class => "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li><a href="<%= new_user_path %>" class="nav-link">S'inscrire</a></li>
            <li><a href="<%= new_session_path %>" class="nav-link">Se connecter</a></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if flash[:success] %>
      <div class="alert alert-success">
        <%= flash[:success]%>
      </div>
    <% end %>
    <% if flash[:danger] %>
      <div class="alert alert-danger">
        <%= flash[:danger]%>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script> 
  </body>
</html>