mySiteRuby/config/routes.rb
Rails.application.routes.draw do

  get 'articles/index', to: 'articles#index', as: :index_articles
  get 'articles/edit', to: 'articles#edit', as: :edit_articles
  
  root to: 'welcome#index', as: :index
  get '/home', to: 'home#index', as: :home

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :articles, only: [:new, :create, :edit, :index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :users, only: [:new, :create, :edit] do
    member do
      get 'confirm'
    end
  end
  
  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users, except: [:show]
  end

end

mySiteRuby/app/models/user.rb
class User < ApplicationRecord

    attr_accessor :avatar_file
    has_many :articles

    has_secure_password
    has_secure_token :confirmation_token
    has_secure_token :recover_password
    
    after_save :avatar_after_upload
    before_save :avatar_before_upload
    after_destroy_commit :avatar_destroy

    validates :name, 
        format: {with: /\A[a-zA-Z0-9_]{2,20}\z/, message: 'ne dois contenir que des caractères alphanumériques ou des "_"'},
        uniqueness: {case_sensitive: false}
    validates :email, 
        format: {with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/, message: 'est invalide'},
        uniqueness: {case_sensitive: false}

    validates :avatar_file, file: {ext: [:jpeg, :jpg, :png]}

    def to_session
        {id: id}
    end

    def avatar_path
        File.join(
            Rails.public_path, 
            self.class.name.downcase.pluralize,
            id.to_s,
            'avatar.jpg'
        )
    end

    def avatar_url
        '/' + [
            self.class.name.downcase.pluralize,
            id.to_s,
            'avatar.jpg'
        ].join('/')
    end 

    private

    def avatar_before_upload 
        if avatar_file.respond_to? :path
            self.avatar = true
        end
    end

    def avatar_after_upload
        path = avatar_path
        if avatar_file.respond_to? :path
            dir = File.dirname(path)
            FileUtils.mkdir_p(dir) unless Dir.exist?(dir)
            image = MiniMagick::Image.new(avatar_file.path) do |b|
                b.resize '150x150^'
                b.gravity 'Center'
                b.crop '150x150+0+0'
            end
            image.format 'jpg'
            image.write path
        end
    end 

    def avatar_destroy 
        dir = File.dirname(avatar_path)
        FileUtils.rm_r(dir) if Dir.exist?(dir)
    end

end

mySiteRuby/app/controllers/admin/users_controller.rb
module Admin

    class UsersController < ApplicationController

        before_action :set_users, only: [:update, :edit, :destroy]

        def index
            @users = User.all
        end

        def new
            @users = User.new
        end

        def create
            @users = User.new(users_params)
            if @users.save
                redirect_to({action: :index}, success: 'L\'utilisateur à bien été créer')
            else 
                render :new
            end
        end

        def edit

        end

        def update
            if @users.update(users_params)
                redirect_to({action: :index}, success: 'L\'utilisateur à bien été modifiée')
            else 
                render :new
            end
        end

        def destroy 
            @users.destroy
            redirect_to({action: :index}, success: 'L\'utilisateur à bien été supprimée')
        end

        private

        def users_params
            params.require(:user).permit(:name, :email, :firstname, :lastname, :avatar_file, :password, :password_confirmation, :motto)
        end

        def set_users
            @users = User.find(params[:id])
        end

    end

end

mySiteRuby/app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]
  before_action :only_signed_out, only: [:new, :create, :confirm]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    @user.recover_password = nil
    if @user.valid?
      @user.save
      UserMailer.confirm(@user).deliver_now
      redirect_to new_user_path, success: 'Votre compte à bien été créer, vous devriez recevoir un email pour confirmer votre compte'
    else
      render 'new'
    end   
  end

  def confirm 
    @user = User.find(params[:id])
    if @user.confirmation_token == params[:token]
      @user.save(validate: false)
      @user.update(confirmed: true, confirmation_token: nil)
      session[:auth] = @user.to_session
      redirect_to profil_path, success: 'Votre compte a bien été confirmé'
    else
      redirect_to new_user_path, danger: 'Ce token ne semble pas valide'
    end 
  end

  def edit 
    @user = current_user
  end

  def update 
    @user = current_user
    user_params = params.require(:user).permit(:name, :email, :firstname, :lastname, :avatar_file, :password, :password_confirmation, :motto)
    if @user.update(user_params)
      redirect_to profil_path, success: 'Votre compte a bien été mis à jour !'
    else
      render :edit
    end
  end

end

mySiteRuby/app/helpers/users_helper.rb
module UsersHelper
end

mySiteRuby/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="mt-3">
  <div class="row justify-content-center">
    <section class="col-lg-5">
      <div class="col-xs-12">
        <h3>Modifier mon compte</h3>
        <%= form_for @user, url: profil_path do |form| %>

          <% if @user.avatar %>
            <%= image_tag @user.avatar_url %>
          <%end%>

          <div class="input-group mb-2">
            <%= form.file_field :avatar_file, placeholder: "Avatar" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.text_field :name, placeholder: "Nom d'utilisateur" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.email_field :email, placeholder: "Email" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.text_field :firstname, placeholder: "Prénom" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.text_field :lastname, placeholder: "Nom" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.text_field :motto, placeholder: "Biographie" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.password_field :password, placeholder: "Mot de passe" , :class => "form-control"%> 
          </div>
          <div class="input-group mb-2">
            <%= form.password_field :password_confirmation, placeholder: "Confirmer le mot de passe" , :class => "form-control"%> 
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Modifier mon compte</button>
          </div>
        <% end %>
      </div>        
    </section>
  </div>
</div>

mySiteRuby/app/views/users/index.html.erb
<div class="container">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user)  %></li>
    <% end %>
  </ul>
</div>

mySiteRuby/app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="mt-3">
  <div class="row justify-content-center">
    <section class="col-lg-5">
      <div class="">
        <div class="col-xs-12">
          <h3>S'inscrire</h3>
          <p class="lead">Inscrivez-vous <span class="text-success">gratuitement</span> dès maintenant</p>
          <%= form_for @user do |form| %>
            <div class="input-group mb-2">
              <%= form.text_field :name, placeholder: "Nom d'utilisateur" , :class => "form-control"%> 
            </div>
            <div class="input-group mb-2">
              <%= form.email_field :email, placeholder: "Email" , :class => "form-control"%> 
            </div>
            <div class="input-group mb-2">
              <%= form.password_field :password, placeholder: "Mot de passe" , :class => "form-control"%> 
            </div>
            <div class="input-group mb-2">
              <%= form.password_field :password_confirmation, placeholder: "Confirmer le mot de passe" , :class => "form-control"%> 
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">S'inscrire</button>
            </div>
          <% end %>
          <div class="form-group">
            <div class="topCushion">Déjà membre ? <a href="<%= new_session_path %>">Se connecter</a></div>
          </diV>
        </div>
      </div>          
    </section>
  </div>
</div>